---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pipeline-limits-tmp
  namespace: limits-tmp
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pipeline-limits-tmp
  namespace: limits-tmp
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-limits-tmp