apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitea-listener-interceptor
  namespace: tekton-pipelines
spec:
  serviceAccountName: pipeline
  triggers:
    - name: foo-trig
      bindings:
        - ref: pipeline-binding
        - ref: message-binding
      template:
        ref: pipeline-template