---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitea-webhook
spec:
  serviceAccountName: pipeline
  triggers:
    - name: gitea-trigger
      # interceptors:
      # - cel:
      #     filter: "body.ref == 'refs/heads/develop'"
      bindings:
        - ref: gitea-triggerbinding
      template:
        ref: test-trigger-template
