---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitea-triggerbinding
spec:
  params:
    - name: servicename
      value: $(body.repository.name)
    - name: gitrevision
      value: $(body.ref)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
