apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-springboot
spec:
  params:
    - name: url
      description: app code git url 
    - name: IMAGE
      description: nexus docker image full path
    - name: CONTEXT_DIR
      description: source code build path
      default: standalone
      type: string
    - name: CONTEXT
      description: file check path
      default: "."
      type: string
    - name: revision
      description: tag,branch,commit_number
      type: string
      default: develop
    - name: SERVICE_NAME
      description: service name == deployment name
      default: changeme
  workspaces:
    - name: maven-settings
      description: maven settings provided as configMap
    - name: source
      description: pvc provided as shared workspace between tasks
  tasks:
    - name: get-code
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.url)"
        - name: revision
          value: "$(params.revision)"
      workspaces:
        - name: source
          workspace: source
    - name: maven-build-lib
      taskRef:
        name: maven
      runAfter:
        - get-code
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
      params:
        - name: CONTEXT_DIR
          value: $(params.CONTEXT_DIR)
        - name: GOALS
          value: 
            - -DskipTests
            - deploy
      when:
        - input: "$(params.CONTEXT_DIR)"
          operator: in
          values: ["shared","."]
    - name: maven-build-app
      taskRef:
        name: maven
      runAfter:
        - get-code
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
      params:
        - name: CONTEXT_DIR
          value: $(params.CONTEXT_DIR)
        - name: GOALS
          value: 
            - -DskipTests
            - clean
            - install
      when:
        - input: "$(params.CONTEXT_DIR)"
          operator: in
          values: ["standalone"]
    - name: dockerfile-check
      taskRef:
        name: file-check
      params:
        - name: CONTEXT
          value: "$(params.CONTEXT)"
      runAfter:
        - get-code
      workspaces:
        - name: source
          workspace: source
    - name: get-build-id
      when:
        - input: "$(params.CONTEXT_DIR)"
          operator: in
          values: ["standalone"]
      taskRef:
        name: generate-build-id-check
      runAfter:
        - get-code
      params:
        - name: CONTEXT_DIR
          value: "$(params.CONTEXT_DIR)"
      workspaces:
        - name: source
          workspace: source
    - name: build-docker-image
      taskRef: 
        name: buildah
      runAfter:
        - maven-build-app
      params:
        - name: IMAGE
          value: "$(params.IMAGE):$(tasks.get-build-id.results.build-id)"
      workspaces:
        - name: source
          workspace: source
    - name: create-helm-chart
      when:
        - input: "$(params.CONTEXT_DIR)"
          operator: in
          values: ["standalone"]
      taskRef:
        name: helm
      runAfter:
        - build-docker-image
      params:
        - name: IMAGE
          value: "$(params.IMAGE)"
        - name: TAG
          value: "$(tasks.get-build-id.results.build-id)"
        - name: SERVICE_NAME
          value: "$(params.SERVICE_NAME)"
      workspaces:
        - name: source
          workspace: source