apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build
spec:
  params:
    - name: CONTEXT_DIR
      description: the context directory from where to build the application
  resources:
    - name: appSource
      type: git
    # - name: appImage
    #   type: image
  tasks:
    - name: maven-build
      taskRef:
        name: maven
      params:
        - name: CONTEXT_DIR
          value: $(params.CONTEXT_DIR)
      resources:
        inputs:
          - name: source
            resource: appSource
        # outputs:
        #   - name: builtImage
        #     resource: appImage
    # - name: deploy-kubernetes-service
    #   taskRef:
    #     name: openshift-client
    #   runAfter:
    #     - build-java-app
    #   resources:
    #     inputs:
    #       - name: source
    #         resource: appSource
    #   params:
    #     - name: ARGS
    #       value:
    #         - "apply"
    #         - "-f"
    #         - "/workspace/source/k8s/deployment.yaml"
    #         - "-f"
    #         - "/workspace/source/k8s/service.yaml"
